Repository kubewarden/github-actions, pull requests merged in 2023-03, with the labels that each got.

#55 fix: Correctly check artifacthub for policies that use tags
  .github/workflows/reusable-release-policy-assemblyscript.yml
  .github/workflows/reusable-release-policy-go.yml
  .github/workflows/reusable-release-policy-rego.yml
  .github/workflows/reusable-release-policy-rust.yml
  .github/workflows/reusable-release-policy-swift.yml
  .github/workflows/reusable-test-policy-assemblyscript.yml
  .github/workflows/reusable-test-policy-go.yml
  .github/workflows/reusable-test-policy-rego.yml
  .github/workflows/reusable-test-policy-rust.yml
  .github/workflows/reusable-test-policy-swift.yml
  check-artifacthub/action.yaml
Labels: kind/bug

#56 fix: Ignore artifacthub fields related with `version`
  .github/workflows/reusable-test-policy-rust.yml
  check-artifacthub/action.yaml
Labels: kind/bug

#57 chore(deps): use latest version of kwctl
  kwctl-installer/action.yaml
Labels: area/dependencies, kind/chore

#60 fix: Ignore lines with `ghcr.io` if not checking version
  check-artifacthub/action.yaml
Labels: kind/bug

#62 fix!: Use `make annotated-policy.wasm` everywhere
  .github/workflows/reusable-release-policy-assemblyscript.yml
  .github/workflows/reusable-release-policy-go.yml
  .github/workflows/reusable-release-policy-rego.yml
  .github/workflows/reusable-release-policy-rust.yml
  .github/workflows/reusable-release-policy-swift.yml
  .github/workflows/reusable-test-policy-assemblyscript.yml
  .github/workflows/reusable-test-policy-go.yml
  .github/workflows/reusable-test-policy-rego.yml
  .github/workflows/reusable-test-policy-rust.yml
  .github/workflows/reusable-test-policy-swift.yml
  policy-build-go/action.yaml
  policy-gh-action-dependencies/action.yaml
Labels: kind/bug, kind/breaking-change

#63 fix: Correctly build Go policies, correctly annotate Rust policies
  .github/workflows/reusable-release-policy-assemblyscript.yml
  .github/workflows/reusable-release-policy-go.yml
  .github/workflows/reusable-release-policy-rego.yml
  .github/workflows/reusable-release-policy-rust.yml
  .github/workflows/reusable-release-policy-swift.yml
  .github/workflows/reusable-test-policy-assemblyscript.yml
  .github/workflows/reusable-test-policy-go.yml
  .github/workflows/reusable-test-policy-rego.yml
  .github/workflows/reusable-test-policy-rust.yml
  .github/workflows/reusable-test-policy-swift.yml
  policy-build-go/action.yaml
  policy-build-rust/action.yaml
  policy-gh-action-dependencies/action.yaml
Labels: kind/bug

#65 fix: speficy `use` references in the proper way
  .github/workflows/reusable-release-policy-assemblyscript.yml
  .github/workflows/reusable-release-policy-go.yml
  .github/workflows/reusable-release-policy-rego.yml
  .github/workflows/reusable-release-policy-rust.yml
  .github/workflows/reusable-release-policy-swift.yml
  .github/workflows/reusable-test-policy-assemblyscript.yml
  .github/workflows/reusable-test-policy-go.yml
  .github/workflows/reusable-test-policy-rego.yml
  .github/workflows/reusable-test-policy-rust.yml
  .github/workflows/reusable-test-policy-swift.yml
  policy-gh-action-dependencies/action.yaml
Labels: kind/bug

#68 fix: Reinstalled deleted @
  .github/workflows/reusable-release-policy-assemblyscript.yml
  .github/workflows/reusable-release-policy-go.yml
  .github/workflows/reusable-release-policy-rego.yml
  .github/workflows/reusable-release-policy-rust.yml
  .github/workflows/reusable-release-policy-swift.yml
  .github/workflows/reusable-test-policy-assemblyscript.yml
  .github/workflows/reusable-test-policy-go.yml
  .github/workflows/reusable-test-policy-rego.yml
  .github/workflows/reusable-test-policy-rust.yml
  .github/workflows/reusable-test-policy-swift.yml
  policy-gh-action-dependencies/action.yaml
Labels: kind/bug

#69 feat: Add push-artifacthub action, push artifacthub files to artifacthub branch
  .github/workflows/reusable-release-policy-assemblyscript.yml
  .github/workflows/reusable-release-policy-go.yml
  .github/workflows/reusable-release-policy-rego.yml
  .github/workflows/reusable-release-policy-rust.yml
  .github/workflows/reusable-release-policy-swift.yml
  .github/workflows/reusable-test-policy-assemblyscript.yml
  .github/workflows/reusable-test-policy-go.yml
  .github/workflows/reusable-test-policy-rego.yml
  .github/workflows/reusable-test-policy-rust.yml
  .github/workflows/reusable-test-policy-swift.yml
  check-artifacthub/action.yml
  kubernetes-bom-installer/action.yml
  kwctl-installer/action.yml
  opa-installer/action.yml
  policy-build-go/action.yml
  policy-build-rust/action.yml
  policy-gh-action-dependencies/action.yml
  policy-release/action.yml
  push-artifacthub/action.yml
  sbom-generator-installer/action.yml
  setup-kubewarden-cluster-action/action.yml
Labels: kind/enhancement
