Repository kubewarden/github-actions, pull requests merged in 2023-07, with the labels that each got.

#78 Updates cosign to v2.
  policy-build-go/action.yml
  policy-build-rust/action.yml
  policy-gh-action-dependencies/action.yml
  policy-release/action.yml
Labels: kind/enhancement, kind/breaking-change, area/ci

#81 chore: prepare for 3.1.5 release
  .github/workflows/reusable-release-policy-assemblyscript.yml
  .github/workflows/reusable-release-policy-go.yml
  .github/workflows/reusable-release-policy-rego.yml
  .github/workflows/reusable-release-policy-rust.yml
  .github/workflows/reusable-release-policy-swift.yml
  .github/workflows/reusable-test-policy-assemblyscript.yml
  .github/workflows/reusable-test-policy-go.yml
  .github/workflows/reusable-test-policy-rego.yml
  .github/workflows/reusable-test-policy-rust.yml
  .github/workflows/reusable-test-policy-swift.yml
  policy-gh-action-dependencies/action.yml
Labels: kind/chore

#82 build: bump tinygo version to 0.28.1
  policy-build-go/action.yml
Labels: area/dependencies, area/ci

#83 chore: prepare for 3.1.6 release
  .github/workflows/reusable-release-policy-assemblyscript.yml
  .github/workflows/reusable-release-policy-go.yml
  .github/workflows/reusable-release-policy-rego.yml
  .github/workflows/reusable-release-policy-rust.yml
  .github/workflows/reusable-release-policy-swift.yml
  .github/workflows/reusable-test-policy-assemblyscript.yml
  .github/workflows/reusable-test-policy-go.yml
  .github/workflows/reusable-test-policy-rego.yml
  .github/workflows/reusable-test-policy-rust.yml
  .github/workflows/reusable-test-policy-swift.yml
  policy-gh-action-dependencies/action.yml
Labels: kind/chore
