Repository kubewarden/github-actions, pull requests merged in 2024-12, with the labels that each got.

#138 feat: Support policies in folders for reusable workflows
  .github/workflows/reusable-release-policy-assemblyscript.yml
  .github/workflows/reusable-release-policy-go-wasi.yml
  .github/workflows/reusable-release-policy-go.yml
  .github/workflows/reusable-release-policy-rego.yml
  .github/workflows/reusable-release-policy-rust.yml
  .github/workflows/reusable-release-policy-swift.yml
  .github/workflows/reusable-test-policy-assemblyscript.yml
  .github/workflows/reusable-test-policy-go-wasi.yml
  .github/workflows/reusable-test-policy-go.yml
  .github/workflows/reusable-test-policy-rego.yml
  .github/workflows/reusable-test-policy-rust.yml
  .github/workflows/reusable-test-policy-swift.yml
  check-artifacthub/action.yml
  opa-installer/action.yml
  policy-gh-action-dependencies/action.yml
  policy-release/action.yml
  push-artifacthub/action.yml
Labels: kind/enhancement

#142 fix: Don't compare version on CI for rust policies
  .github/workflows/reusable-release-policy-assemblyscript.yml
  .github/workflows/reusable-release-policy-go-wasi.yml
  .github/workflows/reusable-release-policy-go.yml
  .github/workflows/reusable-release-policy-rego.yml
  .github/workflows/reusable-release-policy-rust.yml
  .github/workflows/reusable-release-policy-swift.yml
  .github/workflows/reusable-test-policy-assemblyscript.yml
  .github/workflows/reusable-test-policy-go-wasi.yml
  .github/workflows/reusable-test-policy-go.yml
  .github/workflows/reusable-test-policy-rego.yml
  .github/workflows/reusable-test-policy-rust.yml
  .github/workflows/reusable-test-policy-swift.yml
  policy-gh-action-dependencies/action.yml
  push-artifacthub/action.yml
Labels: kind/bug

#143 chore(deps): update version of tinygo
  policy-build-tinygo/action.yml
Labels: area/dependencies, kind/chore

#144 fix: Support repos where there's no tag at all
  .github/workflows/reusable-release-policy-assemblyscript.yml
  .github/workflows/reusable-release-policy-go-wasi.yml
  .github/workflows/reusable-release-policy-go.yml
  .github/workflows/reusable-release-policy-rego.yml
  .github/workflows/reusable-release-policy-rust.yml
  .github/workflows/reusable-release-policy-swift.yml
  .github/workflows/reusable-test-policy-assemblyscript.yml
  .github/workflows/reusable-test-policy-go-wasi.yml
  .github/workflows/reusable-test-policy-go.yml
  .github/workflows/reusable-test-policy-rego.yml
  .github/workflows/reusable-test-policy-rust.yml
  .github/workflows/reusable-test-policy-swift.yml
  policy-gh-action-dependencies/action.yml
Labels: kind/bug
