Repository kubewarden/github-actions, pull requests merged in 2025-03, with the labels that each got.

#159 ci: add renovate config for policies
  renovate-config/policies.json
Labels: area/ci

#160 ci: pin GHA by checksum
  renovate.json
Labels: kind/enhancement

#164 feat!: generate artifacthub-pkg dynamically
  .github/workflows/reusable-release-policy-assemblyscript.yml
  .github/workflows/reusable-release-policy-go-wasi.yml
  .github/workflows/reusable-release-policy-go.yml
  .github/workflows/reusable-release-policy-rego.yml
  .github/workflows/reusable-release-policy-rust.yml
  .github/workflows/reusable-release-policy-swift.yml
  .github/workflows/reusable-test-policy-assemblyscript.yml
  .github/workflows/reusable-test-policy-go-wasi.yml
  .github/workflows/reusable-test-policy-go.yml
  .github/workflows/reusable-test-policy-rego.yml
  .github/workflows/reusable-test-policy-rust.yml
  .github/workflows/reusable-test-policy-swift.yml
  check-artifacthub/action.yml
  check-policy-version/action.yml
  kwctl-installer/action.yml
  policy-gh-action-dependencies/action.yml
  push-artifacthub/action.yml
Labels: kind/enhancement, kind/breaking-change

#168 feat: add policy catalog repository dispatch
  .github/workflows/reusable-release-policy-assemblyscript.yml
  .github/workflows/reusable-release-policy-go-wasi.yml
  .github/workflows/reusable-release-policy-go.yml
  .github/workflows/reusable-release-policy-rego.yml
  .github/workflows/reusable-release-policy-rust.yml
  .github/workflows/reusable-release-policy-swift.yml
  .github/workflows/reusable-test-policy-go-wasi.yml
  .github/workflows/reusable-test-policy-go.yml
  .github/workflows/reusable-test-policy-rego.yml
  .github/workflows/reusable-test-policy-rust.yml
  policy-gh-action-dependencies/action.yml
  policy-release-catalog/action.yml
  push-artifacthub/action.yml
Labels: kind/enhancement

#169 refactor!: convert policy release catalog composite action to reusable workflow
  .github/workflows/reusable-release-policy-assemblyscript.yml
  .github/workflows/reusable-release-policy-catalog.yml
  .github/workflows/reusable-release-policy-go-wasi.yml
  .github/workflows/reusable-release-policy-go.yml
  .github/workflows/reusable-release-policy-rego.yml
  .github/workflows/reusable-release-policy-rust.yml
  .github/workflows/reusable-release-policy-swift.yml
  .github/workflows/reusable-test-policy-go-wasi.yml
  .github/workflows/reusable-test-policy-go.yml
  .github/workflows/reusable-test-policy-rego.yml
  .github/workflows/reusable-test-policy-rust.yml
  policy-gh-action-dependencies/action.yml
  policy-release-catalog/action.yml
  push-artifacthub/action.yml
Labels: kind/breaking-change, area/ci

#170 fix: skip release catalog if ref is not a tag
  .github/workflows/reusable-release-policy-catalog.yml
Labels: kind/bug, area/ci

#171 feat!(release-policy-catalog): generate token programmatically
  .github/workflows/reusable-release-policy-assemblyscript.yml
  .github/workflows/reusable-release-policy-catalog.yml
  .github/workflows/reusable-release-policy-go-wasi.yml
  .github/workflows/reusable-release-policy-go.yml
  .github/workflows/reusable-release-policy-rego.yml
  .github/workflows/reusable-release-policy-rust.yml
  .github/workflows/reusable-release-policy-swift.yml
  .github/workflows/reusable-test-policy-go-wasi.yml
  .github/workflows/reusable-test-policy-go.yml
  .github/workflows/reusable-test-policy-rego.yml
  .github/workflows/reusable-test-policy-rust.yml
  policy-gh-action-dependencies/action.yml
  push-artifacthub/action.yml
Labels: kind/enhancement, kind/breaking-change, area/ci
