Repository kubewarden/github-actions, pull requests merged in 2025-01, with the labels that each got.

#145 fix: Correctly push to artifacthub branch, fix artifacthub policy release
  .github/workflows/reusable-release-policy-assemblyscript.yml
  .github/workflows/reusable-release-policy-go-wasi.yml
  .github/workflows/reusable-release-policy-go.yml
  .github/workflows/reusable-release-policy-rego.yml
  .github/workflows/reusable-release-policy-rust.yml
  .github/workflows/reusable-release-policy-swift.yml
  .github/workflows/reusable-test-policy-assemblyscript.yml
  .github/workflows/reusable-test-policy-go-wasi.yml
  .github/workflows/reusable-test-policy-go.yml
  .github/workflows/reusable-test-policy-rego.yml
  .github/workflows/reusable-test-policy-rust.yml
  .github/workflows/reusable-test-policy-swift.yml
  policy-gh-action-dependencies/action.yml
  push-artifacthub/action.yml
Labels: kind/bug

#146 update tinygo
  .github/workflows/reusable-release-policy-assemblyscript.yml
  .github/workflows/reusable-release-policy-go-wasi.yml
  .github/workflows/reusable-release-policy-go.yml
  .github/workflows/reusable-release-policy-rego.yml
  .github/workflows/reusable-release-policy-rust.yml
  .github/workflows/reusable-release-policy-swift.yml
  .github/workflows/reusable-test-policy-assemblyscript.yml
  .github/workflows/reusable-test-policy-go-wasi.yml
  .github/workflows/reusable-test-policy-go.yml
  .github/workflows/reusable-test-policy-rego.yml
  .github/workflows/reusable-test-policy-rust.yml
  .github/workflows/reusable-test-policy-swift.yml
  policy-build-tinygo/action.yml
  policy-gh-action-dependencies/action.yml
Labels: area/dependencies

#149 fix: temporarily downgrade tinygo version
  policy-build-tinygo/action.yml
Labels: kind/bug

#148 feat(ci): Common renovate bot configuration
  renovate-config/default.json
  renovate.json
Labels: kind/enhancement, area/ci

#150 fix: Correctly pull from artifacthub and push needed files
  .github/workflows/reusable-release-policy-assemblyscript.yml
  .github/workflows/reusable-release-policy-go-wasi.yml
  .github/workflows/reusable-release-policy-go.yml
  .github/workflows/reusable-release-policy-rego.yml
  .github/workflows/reusable-release-policy-rust.yml
  .github/workflows/reusable-release-policy-swift.yml
  .github/workflows/reusable-test-policy-assemblyscript.yml
  .github/workflows/reusable-test-policy-go-wasi.yml
  .github/workflows/reusable-test-policy-go.yml
  .github/workflows/reusable-test-policy-rego.yml
  .github/workflows/reusable-test-policy-rust.yml
  .github/workflows/reusable-test-policy-swift.yml
  policy-gh-action-dependencies/action.yml
  policy-release/action.yml
  push-artifacthub/action.yml
Labels: kind/bug
